#!/usr/bin/env python3
"""Copy the current ECS task definition, changing only the Main image."""

import json
import sys
from pathlib import Path


# RegisterTaskDefinition accepts these fields from DescribeTaskDefinition. Fields
# such as revision, status and taskDefinitionArn are generated by ECS.
REGISTER_FIELDS = {
    "family", "taskRoleArn", "executionRoleArn", "networkMode",
    "containerDefinitions", "volumes", "placementConstraints",
    "requiresCompatibilities", "cpu", "memory", "tags", "pidMode",
    "ipcMode", "proxyConfiguration", "inferenceAccelerators",
    "ephemeralStorage", "runtimePlatform", "enableFaultInjection",
}


def render(current: dict, image: str, expected_family: str) -> dict:
    if current.get("family") != expected_family:
        raise ValueError(f"Unexpected task definition family: {current.get('family')}")
    if "FARGATE" not in current.get("requiresCompatibilities", []):
        raise ValueError("Current task definition is not Fargate compatible")
    if not image.startswith("964862484349.dkr.ecr.us-east-2.amazonaws.com/agenta-backend@sha256:"):
        raise ValueError("Image must be an immutable digest in the smoke ECR repository")
    containers = current.get("containerDefinitions", [])
    if len([item for item in containers if item.get("name") == "Main"]) != 1:
        raise ValueError("Expected exactly one Main container")
    result = {key: value for key, value in current.items()
              if key in REGISTER_FIELDS and value is not None}
    # json roundtrip avoids changing the input object while preserving env,
    # Secrets Manager references, health checks, roles, ports and resources.
    result = json.loads(json.dumps(result))
    for container in result["containerDefinitions"]:
        if container["name"] == "Main":
            container["image"] = image
    return result


if __name__ == "__main__":
    source, destination, image_uri, family = sys.argv[1:]
    current = json.loads(Path(source).read_text())
    Path(destination).write_text(json.dumps(render(current, image_uri, family)))
